const log = console.log;
var Start = Date.now();
var fs = require('fs');
var pages = require('./files');

log('Generating README.md...');
var content;
content = '';

for(let i=0; i<pages.length; i++) {
    log(`Adding ${pages[i]}...`);
    var fc = fs.readFileSync('./files/' + pages[i] + '.md').toString();

    content += fc + '\n';
    log(`Added ${pages[i]}`);
}

log(`Added all pages!`);
log(`Generating footer...`);
content += '\n';
content += '\tDo not edit this file!\n';
content += '\tGenerated at ' + new Date().toLocaleString("en-US");
content += '\n\t© HuiCraft ' + new Date().getFullYear();
log(`Footer generated`);

fs.writeFileSync('./README.MD', content);
var End = Date.now();
log(`\n\tGenerated in ${End-Start} ms!`);